name: Ruff Code Quality Check

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Run Ruff Linter
        uses: astral-sh/ruff-action@v4.1.0